<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    name="Registry"
    targetNamespace="http://unigrids.org/2006/04/services/registry"
    xmlns:registry ="http://unigrids.org/2006/04/services/registry"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsrf-rp="http://docs.oasis-open.org/wsrf/rp-2">

  <wsdl:types>
    <xsd:schema
        targetNamespace="http://unigrids.org/2006/04/services/registry">
	  <xsd:include schemaLocation="Registry.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  <!-- =========== Registry portType ================= -->
  <wsdl:portType name="Registry"
                 wsrf-rp:ResourceProperties="registry:RegistryProperties">
  </wsdl:portType>

</wsdl:definitions>